#ifndef AMPLIFIER_H
#define AMPLIFIER_H

#include <Devices/Device.h>
#include <GeneralClasses/PhysicalConstants.h>

class Amplifier : public Device {
  public:
	Amplifier(Gain G);

	Gain get_Gain();
	Gain get_Loss();
	Power get_Noise();

  private:
	/**
	 * @brief calculate_NoisePower calculates the ASE Noise power generated by the amplifier.
	 */
	void calculate_NoisePower();

	/**
	 * @brief NoiseFigure is the noise figure of the amplifiers.
	 */
	static Gain NoiseFigure;
	/**
	 * @brief BRef is the reference bandwidth. Is a parameter for the ASE Noise modelling.
	 */
	static long double BRef;
	Gain AmplifierGain;
	Power NoisePower;
};

#endif // AMPLIFIER_H
