#ifndef AMPLIFIER_H
#define AMPLIFIER_H

#include <Devices/Device.h>

class Amplifier : public Device {
  public:
    enum AmplifierType {
        LineAmplifierType, BoosterAmplifierType, PreAmplifierType
    };

    static constexpr DeviceType T = Device::AmplifierDevice;

    Amplifier(Gain G);

    Gain get_Loss();
    Power get_Noise();

    void set_Gain(Gain G);

    Gain AmplifierGain;
    Power NoisePower;

  private:
    /**
     * @brief calculate_NoisePower calculates the ASE Noise power generated by the amplifier.
     */
    virtual void calculate_NoisePower() = 0;
};

#endif // AMPLIFIER_H
